# Disable defaults
AllCops:
  TargetRailsVersion: 4.2
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "script/**/*"
    - "tmp/**/*"
    - "uploads/**/*"
    - "vendor/**/*"

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - config/routes.rb
    - config/initializers/simple_form_bootstrap.rb

Metrics/LineLength:
  Enabled: true
  Max: 110

Metrics/MethodLength:
  Enabled: true
  Max: 12
  Exclude:
    - db/migrate/*.rb

# We rely on foreign key constraints to raise errors in some cases, instead
# of using restrict_with_exception.
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/policies/**/*"
    - "app/decorators/**/*"
    - "db/migrate/*.rb"

Style/EmptyLineAfterGuardClause:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - "[]"
    - to
    - not_to
    - require
    - raise
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/deploy.rb
    - config/deploy/**/*.rb
    - db/migrate/*.rb
    - Gemfile*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler:
  Enabled: true

Rails:
  Enabled: true
