require: rubocop-rails

AllCops:
  TargetRailsVersion: 6.0
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "script/**/*"
    - "tmp/**/*"
    - "uploads/**/*"
    - "vendor/**/*"
    - "**/*.erb"

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - lib/**/*.rake
    - spec/**/*
    - config/routes.rb
    - config/initializers/simple_form_bootstrap.rb

Metrics/LineLength:
  Enabled: true
  Max: 110

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - db/migrate/*.rb

# We rely on foreign key constraints to raise errors in some cases, instead
# of using restrict_with_exception.
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  # Sometimes it was telling me to put braces on named params.
  EnforcedStyle: no_braces

Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/decorators/**/*"
    - "app/helpers/**/*"
    - "app/policies/**/*"
    - "app/serializers/**/*"
    - "db/migrate/*.rb"

Style/EmptyMethod:
  EnforcedStyle: expanded

# Sometimes using a series of if/unless blocks in parallel structure is good for readability.
Style/GuardClause:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - "[]"
    - to
    - not_to
    - require
    - raise
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/deploy.rb
    - config/deploy/**/*.rb
    - db/migrate/*.rb
    - Gemfile*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler:
  Enabled: true

Rails:
  Enabled: true
