smtp:
  address: "localhost"
  port: 1025
url:
  # localhost.tv is a public domain that resolves to 127.0.0.1 for all subdomains.
  host: gather.localhost.tv
  port: 3000
  protocol: https
single_sign_on:
  # Not a real secret, ok to check in
  secret: ssosecret
